package Packets;

/**
 * Defines the types of messages exchanged between client and server.
 */
public enum MessageType {
    AUCTION_UPDATE,
    HIGHEST_BID_OWNER_LOST,
    AUCTION_CANCELLED,
    AUCTION_CONCLUDED,
    NOTIFY_AUCTION_WINNER,
    NOTIFY_NO_AUCTION_WINNER,
    AUCTION_ACTION_RESPONSE,
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    DASHBOARD_PAGE_REQUEST,
    DASHBOARD_PAGE_RESPONSE,
    DASHBOARD_STATS_REQUEST,
    DASHBOARD_STATS_RESPONSE,
    AUCTION_DETAIL_REQUEST,
    AUCTION_DETAIL_RESPONSE,
    AUCTION_OWNER_REQUEST,
    AUCTION_OWNER_RESPONSE,
    BID_HISTORY_REQUEST,
    BID_HISTORY_RESPONSE,
    PARTICIPANT_COUNT_REQUEST,
    PARTICIPANT_COUNT_RESPONSE,
    HIGHEST_BIDDER_REQUEST,
    HIGHEST_BIDDER_RESPONSE,
    MY_ACTIVE_BIDS_REQUEST,
    MY_ACTIVE_BIDS_RESPONSE,
    MY_COMPLETED_BIDS_REQUEST,
    MY_COMPLETED_BIDS_RESPONSE,
    USER_HIGHEST_BID_REQUEST,
    USER_HIGHEST_BID_RESPONSE,
    CREATE_AUCTION,
    PLACE_BID,
    CANCEL_AUCTION,
    JOIN_AUCTION,
    LEAVE_AUCTION,
    LIST_AUCTIONS
}
