package Packets;

/**
 * Defines the types of messages exchanged between client and server.
 */
public enum MessageType {
    PING,
    PONG,
    NETWORK_ERROR,
    AUCTION_UPDATE,
    HIGHEST_BID_OWNER_LOST,
    AUCTION_CANCELLED,
    AUCTION_CONCLUDED,
    NOTIFY_AUCTION_WINNER,
    NOTIFY_NO_AUCTION_WINNER,
    AUCTION_ACTION_RESPONSE,
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    LOGOUT_REQUEST,
    LOGOUT_RESPONSE,
    DASHBOARD_PAGE_REQUEST,
    DASHBOARD_PAGE_RESPONSE,
    DASHBOARD_STATS_REQUEST,
    DASHBOARD_STATS_RESPONSE,
    AUCTION_DETAIL_REQUEST,
    AUCTION_DETAIL_RESPONSE,
    AUCTION_OWNER_REQUEST,
    AUCTION_OWNER_RESPONSE,
    BID_HISTORY_REQUEST,
    BID_HISTORY_RESPONSE,
    PARTICIPANT_COUNT_REQUEST,
    PARTICIPANT_COUNT_RESPONSE,
    HIGHEST_BIDDER_REQUEST,
    HIGHEST_BIDDER_RESPONSE,
    MY_ACTIVE_BIDS_REQUEST,
    MY_ACTIVE_BIDS_RESPONSE,
    MY_COMPLETED_BIDS_REQUEST,
    MY_COMPLETED_BIDS_RESPONSE,
    MY_SELLING_ITEMS_REQUEST,
    MY_SELLING_ITEMS_RESPONSE,
    USER_HIGHEST_BID_REQUEST,
    USER_HIGHEST_BID_RESPONSE,
    WALLET_BALANCE_REQUEST,
    WALLET_BALANCE_RESPONSE,
    WALLET_DEPOSIT_REQUEST,
    WALLET_DEPOSIT_RESPONSE,
    PROFILE_STATS_REQUEST,
    PROFILE_STATS_RESPONSE,
    NOTIFICATION_LIST_REQUEST,
    NOTIFICATION_LIST_RESPONSE,
    NOTIFICATION_COUNT_REQUEST,
    NOTIFICATION_COUNT_RESPONSE,
    NOTIFICATION_MARK_READ_REQUEST,
    NOTIFICATION_MARK_READ_RESPONSE,
    NOTIFICATION_MARK_ALL_READ_REQUEST,
    NOTIFICATION_MARK_ALL_READ_RESPONSE,
    PUSH_SUBSCRIBE_REQUEST,
    PUSH_SUBSCRIBE_RESPONSE,
    AUCTION_UPDATE_PUSH,
    NOTIFICATION_PUSH,
    WALLET_UPDATE_PUSH,
    SEARCH_AUCTIONS_REQUEST,
    SEARCH_AUCTIONS_RESPONSE,
    CREATE_AUCTION,
    PLACE_BID,
    CANCEL_AUCTION,
    JOIN_AUCTION,
    LEAVE_AUCTION,
    LIST_AUCTIONS,

    // ========================== Auto-Bid ==========================

    /** Client → Server: Đăng ký cấu hình auto-bid (payload: Map{auctionId, maxBid, increment}). */
    AUTO_BID_REGISTER_REQUEST,
    /** Server → Client: Phản hồi đăng ký auto-bid (payload: Boolean hoặc AutoBidConfig). */
    AUTO_BID_REGISTER_RESPONSE,

    /** Client → Server: Hủy cấu hình auto-bid (payload: auctionId). */
    AUTO_BID_CANCEL_REQUEST,
    /** Server → Client: Phản hồi hủy auto-bid (payload: Boolean). */
    AUTO_BID_CANCEL_RESPONSE,

    /** Client → Server: Xem trạng thái auto-bid hiện tại (payload: auctionId). */
    AUTO_BID_STATUS_REQUEST,
    /** Server → Client: Trả về cấu hình auto-bid (payload: AutoBidConfig hoặc null). */
    AUTO_BID_STATUS_RESPONSE,

    /** Server → Client (Push): Thông báo sự kiện auto-bid (payload: AutoBidNotificationDTO). */
    AUTO_BID_NOTIFICATION
}
